name: Python wheels

on:
  push:
    branches: [ master, pure-python ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        id: setup
        uses: actions/setup-python@v2
        # continue-on-error: true
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        id: requirements
        if: ${{steps.setup.outcome == 'success'}}
        run: |
          python -m pip install --upgrade pip
        # continue-on-error: true
      - name: Build wheel
        id: wheel
        if: ${{steps.requirements.outcome == 'success'}}
        run: |
          python -m pip wheel --wheel-dir ./dist .
        # continue-on-error: true
      - name: Store wheel
        if: ${{steps.wheel.outcome == 'success'}}
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist